# fly.toml app configuration file generated for note8769 on 2023-07-25T13:41:27+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "note8769"
primary_region = "ams"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
